# Generated by Django 3.1.8 on 2023-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.AddField(
            model_name='balance',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
