# Generated by Django 3.1.8 on 2023-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('PayPal', 'PayPal'), ('Amazon Gift Card', 'Amazon Gift Card'), ('Payeer', 'Payeer'), ('Visa Card', 'Visa Card')], max_length=255)),
                ('points_required', models.IntegerField()),
                ('image', models.ImageField(upload_to='cards/')),
                ('description', models.TextField()),
            ],
        ),
    ]
